[package]
name = "dead-man-switch"
version = "0.1.3"
edition = "2021"
authors = ["Jose Storopoli <jose@storopoli.io>"]
description = "A simple no-BS Dead Man's Switch"
license = "AGPL-3.0-only"
readme = "README.md"

[dependencies]
anyhow = "1"
crossterm = "0.27"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
directories-next = "2"
lettre = { version = "0.10", features = ["rustls-tls", "builder"] }
lettre_email = "0.9"
mime_guess = "2"
ratatui = "0.20"
chrono = "0.4"

[profile.release]
opt-level = "z"   # Optimized for size, use 3 for speed
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduced to increase optimizations
panic = "abort"   # Abort on panic
strip = "symbols" # Strip symbols from binary
