name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: null

permissions: {}

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
        with:
          persist-credentials: false

      - name: Build Docker image
        run: docker build -f Dockerfile-web -t dead_man_switch-web .

      - name: Run Docker
        run: docker run -d --name dead_man_switch-web -p 3000:3000 dead_man_switch-web

      - name: Test Docker
        run: |
          sleep 10 # sleep for 10 seconds to allow the server to start
          response=$(curl -s -o /dev/null -w "%{http_code}" localhost:3000/timer)
          if [ "$response" -ne 303 ]; then
              echo "Expected SEE OTHER (REDIRECT) error, but got $response"
              exit 1
          fi

      - name: Display Docker container logs
        run: docker logs dead_man_switch-web

  build-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
        with:
          persist-credentials: false

      - name: Build Docker image
        run: docker build -f Dockerfile-cli -t dead_man_switch-cli .

      - name: Run Docker
        run: docker run -d --name dead_man_switch-cli dead_man_switch-cli

      - name: Display Docker container logs
        run: docker logs dead_man_switch-cli